version: "3"
services:
  emily-ambolt-emily-api-project-75rxjb:
    image: emily-ambolt-emily-api-project-75rxjb
    container_name: emily-ambolt-emily-api-project-75rxjb
    networks:
      - emily-ambolt-emily-api-project-75rxjb-network
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - ${MOUNT1}:/workspace/paralenz-image-classifier/
      - ${MOUNT2}:/workspace/ATKI/
      - ${MOUNT3}:/workspace/MAFA Dataset/
      - ${MOUNT4}:/workspace/train-images/
    runtime: ${RUNTIME}
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    ipc: ${IPC}
networks:
  emily-ambolt-emily-api-project-75rxjb-network:
    name: emily-ambolt-emily-api-project-75rxjb-network
    driver: bridge
